[phases.setup]
cmds = ["corepack enable && corepack prepare pnpm@latest --activate"]

[phases.install]
cmds = ["cd zhezu-app && pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["cd zhezu-app && pnpm build"]

[start]
cmd = "cd zhezu-app && npx next start -p ${PORT:-3000}"
