[phases.setup]
nixPkgs = ["nodejs_20"]
cmds = ["npm i -g pnpm@latest"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "pnpm start -p ${PORT:-3000}"
